#!/usr/bin/env bash
# Zip this skill into a .skill bundle for sharing.
#
#   ./scripts/export-skill.sh              -> ~/Downloads/bs-design-from-tb.skill
#   ./scripts/export-skill.sh /some/dir    -> /some/dir/bs-design-from-tb.skill
#
# Generated/captured sheets are excluded by default: they are large, they are regenerated by
# SETUP / --core, and product app-shells may contain data captured from a running app.
# Pass --with-sheets to include core/ and products/*/app-shell/.

set -euo pipefail

NAME="bs-design-from-tb"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST_DIR="${HOME}/Downloads"
WITH_SHEETS=0

for arg in "$@"; do
  case "$arg" in
    --with-sheets) WITH_SHEETS=1 ;;
    -*) echo "unknown flag: $arg" >&2; exit 1 ;;
    *) DEST_DIR="$arg" ;;
  esac
done

[ -d "$DEST_DIR" ] || { echo "no such directory: $DEST_DIR" >&2; exit 1; }
OUT="${DEST_DIR}/${NAME}.skill"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

mkdir -p "${STAGE}/${NAME}"
cp "${SKILL_DIR}/SKILL.md" "${STAGE}/${NAME}/"
[ -f "${SKILL_DIR}/README.md" ] && cp "${SKILL_DIR}/README.md" "${STAGE}/${NAME}/"
cp -R "${SKILL_DIR}/references" "${STAGE}/${NAME}/"
cp -R "${SKILL_DIR}/scripts" "${STAGE}/${NAME}/"
cp -R "${SKILL_DIR}/lib" "${STAGE}/${NAME}/"

# Always ship the tier map (the thinking); ship generated sheets only on request.
mkdir -p "${STAGE}/${NAME}/core"
cp "${SKILL_DIR}/core/designstack-tier-map.json" "${STAGE}/${NAME}/core/"

# Ship product configs, but not their generated app-shells unless asked.
if [ -d "${SKILL_DIR}/products" ]; then
  for cfg in "${SKILL_DIR}"/products/*/product.config.json; do
    [ -e "$cfg" ] || continue
    slug="$(basename "$(dirname "$cfg")")"
    mkdir -p "${STAGE}/${NAME}/products/${slug}"
    cp "$cfg" "${STAGE}/${NAME}/products/${slug}/"
  done
fi

if [ "$WITH_SHEETS" -eq 1 ]; then
  cp -R "${SKILL_DIR}/core"/*sheet* "${STAGE}/${NAME}/core/" 2>/dev/null || true
  for shell in "${SKILL_DIR}"/products/*/app-shell; do
    [ -d "$shell" ] || continue
    slug="$(basename "$(dirname "$shell")")"
    cp -R "$shell" "${STAGE}/${NAME}/products/${slug}/"
  done
  echo "including sheets — check they hold no real customer data before sharing"
fi

rm -f "$OUT"
( cd "$STAGE" && zip -q -r "$OUT" "$NAME" )

echo "wrote $OUT"
echo "  $(unzip -l "$OUT" | tail -1 | awk '{print $2}') files, $(du -h "$OUT" | cut -f1)"
